apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-depl
spec:
  replicas: 1 # 1 pod
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec: # Pod rules
      containers:
        - name: client
          image: pob944/client # pob944/client if local
---
apiVersion: v1
kind: Service
metadata:
  name: client-srv
spec:
  selector:
    app: client
  ports:
    - name: client
      protocol: TCP
      port: 3000 # NextJS uses 3000
      targetPort: 3000
